### ISSUE TITLE
Create a login and signup page

### ISSUE THREAD

**Issue by bcassellius** [ThManHimself/book-tracker#10]
- [x] user creates a new account or logs into their account
- [x] user can stay logged in (persistent)
- [x] user can click logout

**Comment by watkincw** [comment]
I have filled in the `./public/js/login.js` and `./public/js/logout.js` files while referencing old work. It is possible that there are minor issues that will cause them not to work properly. The files are completed otherwise. I will leave this issue open until we are confident that everything is working correctly.

**Comment by bcassellius** [comment]
logout became non-functional when deployed to Heroku.
